### ISSUE TITLE
Blocked by Mixed-content

### ISSUE THREAD

**Issue by abkfenris** [IrishMarineInstitute/search-erddaps#3]
It looks like any of us who haven't setup SSL for our ERDDAP servers are getting blocked by [mixed-content](https://developers.google.com/web/fundamentals/security/prevent-mixed-content/fixing-mixed-content).

<img width="668" alt="image" src="https://user-images.githubusercontent.com/1296209/63028551-08d6e000-be7d-11e9-87c7-f58e52c7127b.png">

<img width="1284" alt="image" src="https://user-images.githubusercontent.com/1296209/63029958-797efc00-be7f-11e9-8ff5-e49b935f3f61.png">

If `http` servers have open CORS headers, then a regular fetch, rather than using jsonp should get around the issue as `.json` files count as passive mixed-content which should only throw warnings, whereas JSON returned as jsonp callbacks are treated as active mixed-content.

https://github.com/IrishMarineInstitute/search-erddaps/blob/95e7cca8175e0be363b7be45bed7254be9895627/app.js#L38-L52

A quick (not tested) attempt at trying to fetch JSON directly.

```javascript
ERDDAP.prototype.search = function(query){ 
 	var url = this.endpoint + "/search/index.json?"; 
 	var urlParams = new URLSearchParams("?"); 
 	urlParams.set("searchFor",query); 
 	urlParams.set("page",1); 
 	urlParams.set("itemsPerPage",10000); 
        var headers = {'Cache-Control': 'no-cache', 'Pragma': 'no-cache'}
        if (this.endpoint.includes("https")) { 
        	return fetchJsonp(url + urlParams.toString(),{  headers: headers }, jsonpCallback: ".jsonp"}) 
               		.then(function(response) { 
            		return response.json(); 
          		}) 
          		.then(e2o) 
          		.catch(function(x){ 
        			console.log("no results from "+url); 
        		}); 
       } else {
                return fetch(url + urlParams.toString(), { headers } )
                .then(function(response) {
                        return response.json
                })
                .then(e20)
                .catch(function(x) {
                        console.log("no results from " + url);
                });
       }
 } 
```

**Comment by fullergalway** [comment]
Thanks Alex; It seems most of the ERDDAP servers are not configured with open CORS; I will check some options:

 *  Host the search on a non-https site (github pages only supports https)
 * Use the suggested fix for some sites.
 * Identify early the urls which aren't going to work and let the user know.

**Comment by fullergalway** [comment]
This one should work for the moment, I hope:
[http://erddap.com/#search=M01+waves](http://erddap.com/#search=M01+waves)

**Comment by fullergalway** [comment]
Working at http://erddap.com so marking as fixed.
