### ISSUE TITLE
Consolidate erddap server list location

### ISSUE THREAD

**Issue by MathewBiddle** [IrishMarineInstitute/search-erddaps#4]
Just a proposition, feel free to ignore.

Looks like erddapy has a list of servers https://github.com/ioos/erddapy/blob/master/erddapy/utilities.py
and there is a list of servers in this repo https://github.com/IrishMarineInstitute/search-erddaps/blob/master/erddaps.json

Could we consolidate into a master list and put it somewhere? maybe https://github.com/IrishMarineInstitute/awesome-erddap
Then both of these tools could use a master list...

**Comment by adamml** [comment]
Looping @bobsimons

Talking with @fullergalway, we think the best approach to this would be to have a separate repository alongside the main Erddap repo which contains the "master list" as a JSON object.

That could be maintained by pull requests, similarly to the Awesome list, and we could link to it from the Awesome list.

This would allow the two tools you mention @mbiddle-bcodmo to hit off the list, and perhaps @bobsimons could hit his search tool off it too.

And noting that we also had a request by email (and now also see #5) to add the following to our tool...
http://gcoos5.geos.tamu.edu:6060/erddap/
http://gcoos4.tamu.edu:8080/erddap/

**Comment by 7yl4r** [comment]
+1 for a global erddap_list repo with readme & `erddap.json`.
Could then be easily added as a git submodule here, BobSimons/erddap, and elsewhere people might want it.

**Comment by adamml** [comment]
Looping the committers at https://github.com/ioos/erddapy who aren't on this discussion.

@rsignell-usgs; @ocefpaf; & @circularpenguin

**Comment by BobSimons** [comment]
I support the idea, wherever it is.
How about next to awesome-erddap (since I am probably the least skillful with git)?

**Comment by ocefpaf** [comment]
+1 a canonical source for this list would be nice. I believe the R library does something similar.

**Comment by adamml** [comment]
@BobSimons, @ocefpaf, @7yl4r Thanks for your support on this. I'll have a look and see what we can do inside a repo on this organisation.

Following @ocefpaf's comment on the R library, looping the committers there: @sckott; @btupper; @jeroen; @douglatornell; @rmendels; @kwilcox.

**Comment by adamml** [comment]
Some thoughts before we do any work on this:
- The master list will probably need to be a JSON file
- To access the JSON file remotely, we probably need to set the GitHub pages up on the repo
- Some of the applications use a URL to an Erddap instance and a name, some just a URL so the JSON will need both
- The repo should carry instructions, similar to the Awesome list, on how to request updates and additions

**Comment by fullergalway** [comment]
Could just be a .json file (or two) in the awesome-erddap repository?

**Comment by adamml** [comment]
See https://github.com/IrishMarineInstitute/awesome-erddap/pull/5

**Comment by fullergalway** [comment]
Now using awesomeErddaps from:
https://irishmarineinstitute.github.io/awesome-erddap/erddaps.js
Note could also have used:
https://irishmarineinstitute.github.io/awesome-erddap/erddaps.json
