### ISSUE TITLE
GCOOS ERDDAPs

### ISSUE THREAD

**Issue by fgayanilo** [IrishMarineInstitute/search-erddaps#5]
Can you add the following ERDDAP instances on your list? http://gcoos5.geos.tamu.edu:6060/erddap/ and http://gcoos4.tamu.edu:8080/erddap/

**Comment by adamml** [comment]
@fgayanilo Noted - and thanks for the e-mail on this too.

Please also see #4 for an ongoing discussion about the best way to manage this sort of issue in the future across multiple applications which look for the Erddap list.

**Comment by fullergalway** [comment]
Marking this as done, though no response from either of those servers for me.
