### ISSUE TITLE
Correct and new ERDDAP for GCOOS

### ISSUE THREAD

**Issue by fgayanilo** [IrishMarineInstitute/search-erddaps#9]
1. For entry #26, please add label “GCOOS Metoceans: Historical Data”  for ERDDAP at http://gcoos5.geos.tamu.edu:6060/erddap
2. For entry #27, please add label “GCOOS Biological and Socioeconomics” for ERDDAP at http://gcoos4.tamu.edu:8080/erddap
3. Please add a new entry: “GCOOS Metoceans: In Situ Observing System” at http://erddap.gcoos.org:8080/erddap

**Comment by fullergalway** [comment]
Fixed in [awesome-erddap](https://github.com/IrishMarineInstitute/awesome-erddap)
